version: '3.0'

expectations:
  population_size: 5000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sccs_and_historical_cohort
    outputs:
      highly_sensitive:
        cohort: output/input_sccs_and_historical_cohort.csv

  apply_exclusion_criteria:
    run: stata-mp:latest analysis/apply_exclusion_criteria.do 
    needs: [generate_cohort] 
    outputs:
      moderately_sensitive: 
        log: output/logs/apply_exclusion_criteria.log
      highly_sensitive:
        cohort_controls: output/input_historical_controls.csv
        cohort_az_cases: output/input_AZ_cases.csv
        cohort_pfizer_cases: output/input_PF_cases.csv 
        cohort_moderna_cases: output/input_MOD_cases.csv 

  SCCS_first_dose_only_primary_AZ:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do AZ
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_primary_AZ.log
        results: output/tables/results_summary_primary_AZ* 
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_AZ*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_AZ*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_AZ*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_AZ*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_AZ*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_AZ*

  SCCS_first_dose_only_primary_Pfizer:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do PF
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SSCCS_first_dose_only_analyses_neuro_primary_PF.log
        results: output/tables/results_summary_primary_PF* 
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_PF*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_PF*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_PF*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_PF*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_PF*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_PF*

  SCCS_first_dose_only_primary_Moderna:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do MOD 
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_primary_MOD.log
        results: output/tables/results_summary_primary_MOD*
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_MOD*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_MOD*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_MOD*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_MOD*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_MOD*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_MOD*





