version: '3.0'

expectations:
  population_size: 10000
  
actions:

  # extract relevant cohorts 
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sccs_and_historical_cohort
    outputs:
      highly_sensitive:
        cohort: output/input_sccs_and_historical_cohort.csv

  apply_exclusion_criteria:
    run: stata-mp:latest analysis/apply_exclusion_criteria.do 
    needs: [generate_cohort] 
    outputs:
      moderately_sensitive: 
        log: output/logs/apply_exclusion_criteria.log
        denominators: output/tables/denominators*
      highly_sensitive:
        cohort_controls: output/input_historical_controls.csv
        cohort_az_cases: output/input_AZ_cases.csv
        cohort_pfizer_cases: output/input_PF_cases.csv 
        cohort_moderna_cases: output/input_MOD_cases.csv 

  # main analyses 
  SCCS_first_dose_only_primary_AZ:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do AZ
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_primary_AZ.log
        results: output/tables/results_summary_primary_AZ* 
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_AZ*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_AZ*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_AZ*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_AZ*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_AZ*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_AZ*

  SCCS_first_dose_only_primary_PF:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do PF 
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_primary_PF.log
        results: output/tables/results_summary_primary_PF*
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_PF*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_PF*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_PF*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_PF*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_PF*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_PF*

  SCCS_first_dose_only_primary_MOD:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_primary.do MOD 
    needs: [apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_primary_MOD.log
        results: output/tables/results_summary_primary_MOD*
      highly_sensitive:
        sccs_pop_BP: output/temp_data/sccs_popn_BP_MOD*
        sccs_pop_TM: output/temp_data/sccs_popn_TM_MOD*
        sccs_pop_GBS: output/temp_data/sccs_popn_GBS_MOD*
        sccs_cutp_BP: output/temp_data/sccs_cutp_data_BP_MOD*
        sccs_cutp_TM: output/temp_data/sccs_cutp_data_TM_MOD*
        sccs_cutp_GBS: output/temp_data/sccs_cutp_data_GBS_MOD*

  # baseline tables (AZ and PF only due to small MOD numbers)
  SCCS_baseline_tables_AZ:
    run: stata-mp:latest analysis/SCCS_baseline_tables.do AZ
    needs: [SCCS_first_dose_only_primary_AZ] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_baseline_tables_AZ.log
        tables: output/tables/baseline_AZ/*

  SCCS_baseline_tables_PF:
    run: stata-mp:latest analysis/SCCS_baseline_tables.do PF
    needs: [SCCS_first_dose_only_primary_PF] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_baseline_tables_PF.log
        tables: output/tables/baseline_PF/*

  SCCS_baseline_tables_MOD:
    run: stata-mp:latest analysis/SCCS_baseline_tables.do MOD
    needs: [SCCS_first_dose_only_primary_MOD] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_baseline_tables_MOD.log
        tables: output/tables/baseline_MOD/*

  # check assumptions 
  SCCS_assumption_checking_AZ:
    run: stata-mp:latest analysis/SCCS_assumption_checking.do AZ
    needs: [SCCS_first_dose_only_primary_AZ] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_assumption_checking_AZ.log
        plots_S1: output/plots/S1_exposure_centered_interval_AZ*
        plots_S2: output/plots/S2_censored_futime_AZ*

  SCCS_assumption_checking_PF:
    run: stata-mp:latest analysis/SCCS_assumption_checking.do PF
    needs: [SCCS_first_dose_only_primary_PF] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_assumption_checking_PF.log
        plots_S1: output/plots/S1_exposure_centered_interval_PF*
        plots_S2: output/plots/S2_censored_futime_PF*

  SCCS_assumption_checking_MOD:
    run: stata-mp:latest analysis/SCCS_assumption_checking.do MOD
    needs: [SCCS_first_dose_only_primary_MOD] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_assumption_checking_MOD.log
        plots_S1: output/plots/S1_exposure_centered_interval_MOD*
        plots_S2: output/plots/S2_censored_futime_MOD*

  # sensitivity analyses 
  ## stratified analyses 
  SCCS_stratified_analyses_AZ:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_stratified.do AZ
    needs: [SCCS_first_dose_only_primary_AZ] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_sens_stratified_AZ.log
        results: output/tables/results_summary_stratified_AZ.csv

  SCCS_stratified_analyses_PF:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_stratified.do PF
    needs: [SCCS_first_dose_only_primary_PF] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_sens_stratified_PF.log
        results: output/tables/results_summary_stratified_PF.csv

  ## changing risk windows 
  SCCS_vary_risk_windows_AZ:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_risk.do AZ
    needs: [SCCS_first_dose_only_primary_AZ] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_sens_risk_AZ.log
        results: output/tables/results_summary_sens_risk_AZ.csv

  SCCS_vary_risk_windows_PF:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_risk.do PF
    needs: [SCCS_first_dose_only_primary_PF] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_neuro_sens_risk_PF.log
        results: output/tables/results_summary_sens_risk_PF.csv

  ## second doses 
  SCCS_second_dose_AZ:
    run: stata-mp:latest analysis/SCCS_first_second_dose_analyses_neuro.do AZ
    needs: [SCCS_first_dose_only_primary_AZ, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_second_dose_analyses_neuro_AZ.log
        results: output/tables/results_summary_second_doses_AZ.csv

  SCCS_second_dose_PF:
    run: stata-mp:latest analysis/SCCS_first_second_dose_analyses_neuro.do PF
    needs: [SCCS_first_dose_only_primary_PF, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_second_dose_analyses_neuro_PF.log
        results: output/tables/results_summary_second_doses_PF*

  ## AZ vs Pfizer 
  SCCS_comparative_AZ_Pfizer:
    run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_sens_AZ_vs_PF.do 
    needs: [SCCS_first_dose_only_primary_AZ, SCCS_first_dose_only_primary_PF] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_first_dose_only_analyses_sens_AZ_vs_PF.log
        results: output/tables/results_summary_sens_AZ_vs_PF.csv

  ## Check for overlap 
  SCCS_overlap_check_AZ:
    run: stata-mp:latest analysis/SCCS_check_all_outcome_overlaps_and_distn_source_BP.do AZ
    needs: [SCCS_first_dose_only_primary_AZ, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_check_all_outcome_overlaps_and_distn_source_BP_AZ.log

  SCCS_overlap_check_PF:
    run: stata-mp:latest analysis/SCCS_check_all_outcome_overlaps_and_distn_source_BP.do PF
    needs: [SCCS_first_dose_only_primary_PF, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_check_all_outcome_overlaps_and_distn_source_BP_PF.log

  SCCS_overlap_check_MOD:
    run: stata-mp:latest analysis/SCCS_check_all_outcome_overlaps_and_distn_source_BP.do MOD
    needs: [SCCS_first_dose_only_primary_MOD, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_check_all_outcome_overlaps_and_distn_source_BP_MOD.log

  ## Sensitivity - censoring and second dose 
  SCCS_censor_2dose_AZ:
   run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_censor_at2nd_dose.do AZ
   needs: [SCCS_first_dose_only_primary_AZ, apply_exclusion_criteria] 
   outputs:
     moderately_sensitive: 
       log: output/logs/SCCS_first_dose_only_sens_censor_at2nd_dose_AZ.log
       results: output/tables/results_summary_sens_censor_at2nd_dose_AZ.csv

  SCCS_censor_2dose_PF:
   run: stata-mp:latest analysis/SCCS_first_dose_only_analyses_neuro_sens_censor_at2nd_dose.do PF
   needs: [SCCS_first_dose_only_primary_PF, apply_exclusion_criteria] 
   outputs:
    moderately_sensitive: 
       log: output/logs/SCCS_first_dose_only_sens_censor_at2nd_dose_PF.log
       results: output/tables/results_summary_sens_censor_at2nd_dose_PF.csv

  SCCS_postvacc2dose_AZ:
    run: stata-mp:latest analysis/SCCS_sens_2nd_dose_only_postvaccbase.do AZ
    needs: [SCCS_first_dose_only_primary_AZ, apply_exclusion_criteria] 
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_sens_2nd_dose_only_postvaccbase_AZ.log
        results: output/tables/results_summary_sens_2nd_dose_only_postvaccbase_AZ.csv

  SCCS_postvacc2dose_PF:
    run: stata-mp:latest analysis/SCCS_sens_2nd_dose_only_postvaccbase.do PF
    needs: [SCCS_first_dose_only_primary_PF, apply_exclusion_criteria]   
    outputs:
      moderately_sensitive: 
        log: output/logs/SCCS_sens_2nd_dose_only_postvaccbase_PF.log
        results: output/tables/results_summary_sens_2nd_dose_only_postvaccbase_PF.csv

